In [1]:
import pandas as pd

In [2]:
# scraping fbref for latest Liverpool stats from 24/25 season
liverpool_df = pd.read_html('https://fbref.com/en/squads/822bd0ba/Liverpool-Stats',
                            attrs={"id":"stats_standard_9"})[0]

In [6]:
# print first 5 rows in dataset
liverpool_df.head(5)

    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Player             Nation                Pos
0      Virgil van Dijk             nl NED                 DF
1     Ryan Gravenberch             nl NED                 MF
2        Mohamed Salah             eg EGY                 FW
3   Dominik Szoboszlai             hu HUN                 MF
4  Alexis Mac Allister             ar ARG                 MF

  Unnamed: 3_level_0 Unnamed: 4_level_0 Playing Time             Performance  \
                 Age                 MP       Starts    Min  90s         Gls
0             33-078                  5            5  450.0  5.0         0.0
1             22-131                  5            5  449.0  5.0         0.0
2             32-101                  5            5  442.0  4.9         3.0
3             23-335                  5            5  420.0  4.7         0.0
4             25-275                  5            5  419.0  4.7         0.0

        ... Per 90 Minutes                                              \
   Ast  ...            Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG
0  0.0  ...           0.00  0.00  0.00   0.00  0.03  0.01   0.04  0.03
1  0.0  ...           0.00  0.00  0.00   0.00  0.01  0.04   0.05  0.01
2  4.0  ...           0.81  1.43  0.61   1.43  0.51  0.40   0.92  0.51
3  1.0  ...           0.21  0.21  0.00   0.21  0.10  0.22   0.32  0.10
4  0.0  ...           0.00  0.00  0.00   0.00  0.04  0.19   0.23  0.04

           Unnamed: 33_level_0
  npxG+xAG             Matches
0     0.04             Matches
1     0.05             Matches
2     0.92             Matches
3     0.32             Matches
4     0.23             Matches

[5 rows x 34 columns]

In [7]:
# printing last 5 rows in dataset
liverpool_df.tail(5)

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
               Player             Nation                Pos
20        Wataru Endo             jp JPN                 MF
21          Joe Gomez            eng ENG                 DF
22    Vitezslav Jaros             cz CZE                 GK
23        Squad Total                NaN                NaN
24     Opponent Total                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0 Playing Time             Performance  \
                  Age                 MP       Starts    Min  90s         Gls
20             31-228                  1            0    1.0  0.0         0.0
21             27-124                  0            0    NaN  NaN         NaN
22             23-063                  0            0    NaN  NaN         NaN
23               27.5                  5           55  450.0  5.0        10.0
24               26.3                  5           55  450.0  5.0         1.0

         ... Per 90 Minutes                                            \
    Ast  ...            Ast  G+A G-PK G+A-PK    xG   xAG xG+xAG  npxG
20  0.0  ...            0.0  0.0  0.0    0.0  0.00  0.00   0.00  0.00
21  NaN  ...            NaN  NaN  NaN    NaN   NaN   NaN    NaN   NaN
22  NaN  ...            NaN  NaN  NaN    NaN   NaN   NaN    NaN   NaN
23  9.0  ...            1.8  3.8  2.0    3.8  1.97  1.71   3.68  1.97
24  1.0  ...            0.2  0.4  0.2    0.4  0.78  0.69   1.47  0.78

            Unnamed: 33_level_0
   npxG+xAG             Matches
20     0.00             Matches
21      NaN             Matches
22      NaN             Matches
23     3.68                 NaN
24     1.47                 NaN

[5 rows x 34 columns]

In [12]:
liverpool_df.col

MultiIndex([( 'Unnamed: 0_level_0',   'Player'),
            ( 'Unnamed: 1_level_0',   'Nation'),
            ( 'Unnamed: 2_level_0',      'Pos'),
            ( 'Unnamed: 3_level_0',      'Age'),
            ( 'Unnamed: 4_level_0',       'MP'),
            (       'Playing Time',   'Starts'),
            (       'Playing Time',      'Min'),
            (       'Playing Time',      '90s'),
            (        'Performance',      'Gls'),
            (        'Performance',      'Ast'),
            (        'Performance',      'G+A'),
            (        'Performance',     'G-PK'),
            (        'Performance',       'PK'),
            (        'Performance',    'PKatt'),
            (        'Performance',     'CrdY'),
            (        'Performance',     'CrdR'),
            (           'Expected',       'xG'),
            (           'Expected',     'npxG'),
            (           'Expected',      'xAG'),
            (           'Expected', 'npxG+xAG'),
            (        'Progression',     'PrgC'),
            (        'Progression',     'PrgP'),
            (        'Progression',     'PrgR'),
            (     'Per 90 Minutes',      'Gls'),
            (     'Per 90 Minutes',      'Ast'),
            (     'Per 90 Minutes',      'G+A'),
            (     'Per 90 Minutes',     'G-PK'),
            (     'Per 90 Minutes',   'G+A-PK'),
            (     'Per 90 Minutes',       'xG'),
            (     'Per 90 Minutes',      'xAG'),
            (     'Per 90 Minutes',   'xG+xAG'),
            (     'Per 90 Minutes',     'npxG'),
            (     'Per 90 Minutes', 'npxG+xAG'),
            ('Unnamed: 33_level_0',  'Matches')],
           )